### PR TITLE
Bump fedora, python and remove click

### PR DESCRIPTION
**Pull request by ashwindasr**
- Bump fedora to `36`
- Bump python to `3.10`
- `click` is installed from doozer dependency. Its causing a conflict if `click` is also defined in requirements.txt in art-bot

### CODE REVIEW

**Comment by ashwindasr** [comment]
Successful build [completed](https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/k8s/ns/art-build-dev/builds/art-bot-base-11)

**Comment by ashwindasr** [comment]
Need to run `art-bot-base` build after PR merge and re-run `art-bot update` build

**Comment by ashwindasr** [comment]
Successful build [completed](https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/k8s/ns/art-build-dev/builds/art-bot-base-14/logs)

**Review by locriandev — APPROVED** [review]

**Comment by locriandev** [comment]
Actually I was thinking... why do we install `doozer` and `elliott` in the container only? Wouldn't it make sense to move what's needed in `requirements.txt` to make explicit what we're using, and remove dependencies from other tools?

**Comment by ashwindasr** [comment]
Good idea, I'll try moving it to `requirements.txt`

**Comment by ashwindasr** [comment]
Hmm, the issue is that if we change anything in doozer/elliott, we also want it to reflect here right. And they are running with older dependency versions than art-bot

**Comment by ashwindasr** [comment]
We can discuss about this further and create a separate PR

**Comment by ashwindasr** [comment]
Theres an issue in production with this change. Putting it off for now, planning to write some functional tests first.

**Pull request merged**
